### PR TITLE
Add controller folder and created callback to handle todo_posts with …

### PR DESCRIPTION
**Pull request by fjuren**
…validation & sanitization using express-validator. Updated front-end form with new label

### CODE REVIEW

**Comment by fjuren** [comment]
I should double check the validation is working again for we merge this

**Comment by fjuren** [comment]
> I should double check the validation is working again before we merge this

Seems to be working. Also added another commit to this PR which includes related changes that were made to client side.

**Review by sudo-dave — APPROVED** [review]

**Review by BrutchsamaJeanLouis — APPROVED** [review]
This code is in working state so I'll just approve it.
Areas of improvement: Better error handled on database calls etc either try catch or callbacks

**Review by matthew-defusco — COMMENTED** [review]
I like the code splitting into a separate controller! Maybe we can think about formally using an MVC design at some point.

Only comment I have is that it looks like you updated the routes to just go to "/" instead of "/todos". Was there a reason for this? I was thinking it makes sense to have our routes be descriptive of the resources they access but didn't know if there was another reason for the update I didn't know about.

**Pull request merged**
